language: ruby
rvm:
  - 2.3.1

services:
  - postgresql

before_script:
  - psql -c 'create database makerspacerepo;' -U postgres
  - openssl req -x509 -newkey rsa:4096 -keyout certs/saml.key -out certs/saml.crt -days 1 -nodes -subj "/C=CA/ST=Ontario/L=Ottawa/O=uOttawa/OU=Richard L'Abbé Makerspace/CN=makerepo.com/emailAddress=travis-ci@makerepo.com"

jobs:
  include:
    - stage: test
      name: "Test"
      script:
        - bundle exec rake db:migrate RAILS_ENV=test
        - bundle exec rake test RAILS_ENV=test
    - stage: deploy
      name: "Deploy"
      script:
        - openssl aes-256-cbc -k $DEPLOY_KEY -d -a -in config/deploy_id_rsa_enc_travis -out config/deploy_id_rsa
        - chmod 600 config/deploy_id_rsa
        - eval "$(ssh-agent -s)"
        - ssh-add config/deploy_id_rsa
        - bundle exec cap staging deploy

env:
  global:
    secure: cYHSnZALsU476xWGqw+Yjovx6YR6cyc/uammbzYuxV7ltcqojriTgAo2QkAWK/ZZQASjgkGIUV18gqchPbPXbw/A6RFppNKv1nwSMzy64JQiq7tqU22Pu0JEbd+h99j47SyYDPzLSr7KPxdmoUUbJPx/+8A6seKFsfrU7Hrtcagvun8gAgcxcSR2t4U8UIdiR4VNn15XkCfaTLXzApGQaLKAvGdYT2MNL1kIRNWqa69Xh7UqagNgwVRMLmgNbgZ/EC77+N3u4hGl/C+GcN6VhIR9JGXQIrBVfOD5P6TP/XQe/gMvd5BkN2RiiDYZ5ImKNp9XDJ1598By68JexYzOlwt0VKawvBu7JKcTfsZFUdrbabDCDW8GxrTWphMKolbv5ZrgMrYP+0fbhh1hCzeMC1+k7d9lbrrBkNU/fABKdbhAx3bT7pmoaY9X+xuxKEpVCvF1T1z4XbcRp7hbEwGtZM7W4LtO2BqI81ktG8X7n3jRjOogFPhFikN6m797Y0LWWwLoZv3aqW50ZylO3pLa0ZnDoYHH8P4dxs6p2F4xlEm8Lmbg8ymHTlQoGH+cms7yfmnp06ENR3qqqQdda7ppp+/O+1lp2W4Wc1UgjL/Z4xY+0pX3u3ZYlKqUhAS/bzAvu4hdF2TX8SJWSTgh1a8zqFfWhz0cgTufs+JX4ljYE8E=

stages:
#  - name: test
  - name: deploy
    if: branch = travis-auto-deploy