language: ruby
rvm:
- 2.3.1

services:
- postgresql

before_script:
- psql -c 'create database makerspacerepo;' -U postgres
- openssl req -x509 -newkey rsa:4096 -keyout certs/saml.key -out certs/saml.crt -days 1 -nodes -subj "/C=CA/ST=Ontario/L=Ottawa/O=uOttawa/OU=Richard L'Abbé Makerspace/CN=makerepo.com/emailAddress=travis-ci@makerepo.com"

jobs:
  include:
  - stage: test
    name: Test
    script:
    - bundle exec rake db:migrate RAILS_ENV=test
    - bundle exec rake test RAILS_ENV=test
  - stage: deploy
    name: Deploy
    script:
    - openssl aes-256-cbc -k $DEPLOY_KEY -d -a -in config/deploy_id_rsa_enc_travis -out config/deploy_id_rsa
    - chmod 600 config/deploy_id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add config/deploy_id_rsa
    - bundle exec cap staging deploy

stages:
- name: test
- name: deploy
  if: branch = develop