default: &default
  adapter: postgresql
  database: makerspacerepo
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
