default: &default
  adapter: postgresql
  database: nicolasgnyra
  username: nicolasgnyra
  host: localhost
  port: 5432

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
