default: &default
  adapter: postgresql
  database: <%= ENV["DB_NAME"] || "makerspacerepo" %>
  username: <%= ENV["DB_USERNAME"] || "postgres" %>
  password: <%= ENV["DB_PASSWORD"] || "postgres" %>
  host: <%= ENV["DB_HOST"] || "localhost" %>
  port: <%= ENV["DB_PORT"] || 5432 %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
