name: CI
on: [push, pull_request]

env:
  DB_HOST: localhost
  DB_USERNAME: postgres
  DB_PASSWORD: postgres

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: makerspacerepo_test        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports: 
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.3
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn install
      - name: Build and run tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/makerspacerepo_test
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
          #RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          mkdir certs && touch certs/saml.key && touch certs/saml.crt
          openssl req -x509 -newkey rsa:4096 -keyout certs/saml.key -out certs/saml.crt -days 1 -nodes -subj "/C=CA/ST=Ontario/L=Ottawa/O=uOttawa/OU=Richard L'Abbé Makerspace/CN=makerepo.com/emailAddress=travis-ci@makerepo.com"
          bundle exec rails db:prepare
          bundle exec rails db:migrate
          bundle exec rails spec
          bundle exec rails test

        
      
